#################################################################
## Commandline switches
#################################################################
- platform: command_line
  switches:
    mac_mini:
      friendly_name: "Mac Mini"
      command_on: "wakeonlan a8:20:66:11:74:81"
      command_off: "ssh twelve@192.168.1.103 pmset sleepnow"
      command_state: "ping -c 192.168.1.103"
