#################################################################
## Wake-on-lan switch
#################################################################
- platform: wake_on_lan
  name: "MacMini Wake-on-LAN"
  mac_address: "a8:20:66:11:74:81"
  host: !secret ip_macmini
  turn_off:
    service: shell_command.sleep_macmini
#- platform: wake_on_lan
#  name: "NUC Wake-on-LAN"
#  mac_address: "94:c6:91:15:b2:e1"
#  host: !secret ip_nuc
#  turn_off:
#    service: shell_command.sleep_nuc