#################################################################
## Wake-on-lan switch
#################################################################
- platform: wake_on_lan
  name: "Mac Mini Wake-on-LAN"
  mac_address: "a8:20:66:11:74:81"
  host: !secret ip_macmini
  turn_off:
    service: shell_command.sleep_macmini
