- id: Updater
  alias: Send notifications when Home Assistant update available
  trigger:
  - entity_id: binary_sensor.updater
    from: 'off'
    platform: state
    to: 'on'
  action:
  - data:
      message: Update for Home Assistant is available.
    service: notify.notify
- id: Lights-Come-Home
  alias: Turn on light when I come home
  description: ''
  trigger:
  - entity_id: person.roman
    from: not_home
    platform: state
    to: home
  condition: []
  action:
  - entity_id: scene.evening_lights_office
    service: scene.turn_on
  - data: {}
    entity_id: scene.evening_lights_bedroom
    service: scene.turn_on
  mode: single
- id: '1594405968922'
  alias: Update the updater
  description: ''
  trigger:
  - event: sunrise
    platform: sun
  - event: sunset
    platform: sun
  condition: []
  action:
  - data: {}
    entity_id: binary_sensor.updater
    service: homeassistant.update_entity
- id: '1608227119048'
  alias: Home Assistant Restart Notification
  description: ''
  use_blueprint:
    path: gregoryduckworth/restart_notification.yaml
    input:
      notify_device: 747c7c86263f4403a0ddc4facf672489
