- alias: 'Set dark theme for the night'
  initial_state: True
  trigger:
    - platform: sun
      event: sunset
  condition:
    - condition: state
      entity_id: input_boolean.auto_darktheme
      state: 'on'
  action:
    - service: frontend.set_theme
      data:
        name: 'dark'

- alias: 'Set default theme for the day'
  initial_state: True
  trigger:
    - platform: sun
      event: sunrise
  condition:
    - condition: state
      entity_id: input_boolean.auto_darktheme
      state: 'on'
  action:
    - service: frontend.set_theme
      data:
        name: 'default'

- alias: 'Change Current Theme'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: input_select.current_theme
  action:
    - service: frontend.set_theme
      data_template:
        name: '{{states.input_select.current_theme.state}}'
