homeassistant:
# Set this in GUI since 0.94
  # Name of the location where Home Assistant is running
#  name: Home
  # Location required to calculate the time the sun rises and sets
#  latitude: !secret geo_lattitude_home
#  longitude: !secret geo_longitude_home
  # Impacts weather/sunrise data (altitude above sea level in meters)
#  elevation: 123
  # metric for Metric, imperial for Imperial
#  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
#  time_zone: Europe/Moscow

  customize: !include customize.yaml
  packages: !include_dir_named packages
  auth_providers:
    - type: homeassistant
#    - type: legacy_api_password
#      api_password: !secret http_password

# Default Config was introduced in 0.88
default_config:
# System Health was introduced in 0.87
# Included in default_config
system_health:
# Enables configuration UI
# Included in default_config
config:
# Cloud allows you to quickly integrate your local Home Assistant with
# various cloud services like Amazon Alexa and Google Assistant
# Included in default_config
cloud:
# Enables the frontend
# Included in default_config
frontend:
  themes: !include_dir_merge_named themes
# Simple Service Discovery Protocol integration introduced in 0.94
# Included in default_config
ssdp:
# Scan the network for supported devices and mDNS services
# Included in default_config
zeroconf:

# Tracks everything that is going on within Home Assistant - moved to Packages
# Included in default_config
#history:
#!include logbook_history.yaml
# Filter events in a logbook
# Included in default_config
#logbook:
#!include logbook_history.yaml
# Enables support for tracking state changes over time
#recorder:
#!include recorder.yaml


# Enables a map showing the location of tracked devices
# Included in default_config
map:
# Track the sun
# Included in default_config
#sun:
# Mobile app support
# Included in default_config
mobile_app:
# The person integration allows connecting device tracker entities to
# one or more person entities.
# Included in default_config
person:
# Checks for available updates
# Included in default_config
updater:
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# The conversation integration allows you to converse with Home Assistant.
# You can either converse by pressing the microphone in the frontend (supported browsers only, no iOS)
# or by calling the conversation/process service with the transcribed text.
conversation:
# Live Camera Stream for Lovelace Picture was introduced in 0.90
stream:
# Discover some devices automatically https://www.home-assistant.io/integrations/discovery/
discovery:
  enable:
# Homekit is enabled by default since 0.94
#    - homekit
#    - yeelight
  ignore:
#    - yeelight
#uPNP Integration enables you to collect network statistics from your router
upnp:
#  sensors: true
#  local_ip: !secret hassio_ip

# HTTP serves all files and data required for the Home Assistant frontend
http:
#  base_url: !secret https_baseurl
  ip_ban_enabled: true
  login_attempts_threshold: 5


# Enables companion component for the Home Assistant iOS app
#ios:

# Enables HomeKit
homekit:
  filter:
    include_domains:
      - media_player
      - light
      - switch
      - camera
      - fan
    exclude_entities:
      - switch.transmission_switch
  entity_config:
    media_player.onkyo_receiver:
      feature_list:
        - feature: on_off
    media_player.itunes:
      feature_list:
        - feature: on_off
        - feature: play_pause
        - feature: play_stop
        - feature: toggle_mute

# Embed Hass.IO add-ons, allows to add additional panels to
# your Home Assistant frontend sidebar
panel_iframe:
  mdiindex:
    title: MDI Icon Index
    icon: mdi:vector-square
#   url: https://cdn.rawgit.com/james-fry/home-assistant-mdi/efd95d7a/home-assistant-mdi.html
    url: https://dev.materialdesignicons.com/icons
#    url: https://materialdesignicons.com/
  transmission:
    title: Transmission
    icon: mdi:car-shift-pattern
    url: !secret transmission_url
#  kodi:
#    title: Kodi
#    icon: mdi:theater
#    url: !secret rpi4_kodi_url

# Log setup - moved to Packages
# Log Severities: notset, debug, info, warn, warning, error, fatal, critical
#logger:
#  default: info
#  logs:
#    homeassistant.components.light.yeelight: warning
#    homeassistant.components.vacuum: critical
#    homeassistant.components.media_player.itunes: critical
#    homeassistant.components.media_player.onkyo: debug
#    homeassistant.components.fan: warning
#    homeassistant.components.fan.xiaomi_miio: warning
#    onkyo: debug
#    miio: warning

# Enables WOL service - moved to Packages
#wake_on_lan:

# Includes:
automation: !include automations.yaml
binary_sensor: !include binary_sensors.yaml
fan: !include fans.yaml
group: !include groups.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
shell_command: !include shell_commands.yaml
input_select: !include input_select.yaml
input_boolean: !include input_boolean.yaml
input_text: !include input_text.yaml
input_number: !include input_number.yaml
input_datetime: !include input_datetime.yaml
weather: !include weather.yaml

camera: !include_dir_merge_list cameras/
switch: !include_dir_merge_list switches/
media_player: !include_dir_merge_list mediaplayers/
sensor: !include_dir_merge_list sensors/

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say
  - platform: yandextts
    api_key: !secret key_yandextts
    language: 'ru-RU'
    codec: mp3
    voice: zahar
    emotion: good
    speed: 2

# Setting zones
zone:
  name: Home
  latitude: !secret geo_lattitude_home
  longitude: !secret geo_longitude_home
  radius: 100
  icon: mdi:home
zone 2:
  name: Office
  latitude: !secret geo_lattitude_office
  longitude: !secret geo_longitude_office
  radius: 200
  icon: mdi:worker
zone 3:
  name: Khimki
  latitude: !secret geo_lattitude_khimki
  longitude: !secret geo_longitude_khimki
  radius: 200
  icon: mdi:home

# Yeelight - moved to Packages
#yeelight: !include yeelight.yaml
#light:
#  - platform: group
#    name: All Lights
#    entities:
#      - light.living_room
#      - light.night_light
#      - light.table_light

# Speedtest.com
speedtestdotnet:
  scan_interval:
    minutes: 30


# since 0.100 install MQTT-addon, create mqtt-user in Users and use Integrations:
# Mosquitto broker
#mqtt:
#  broker: localhost
#  discovery: true
#  discovery_prefix: homeassistant


# Keenetic device tracker
device_tracker:
#  - platform: keenetic_ndms2
#    host: !secret keenetic_ip
#    username: !secret keenetic_user
#    password: !secret keenetic_password
#    interval_seconds: 180
#    consider_home: 0:15
#    new_device_defaults:
#      track_new_devices: false
  - platform: bluetooth_tracker
    consider_home: 0:03
    request_rssi: true
#  - platform: bluetooth_le_tracker
#    track_new_devices: true
  - platform: nmap_tracker
    hosts: 192.168.1.1/24
    home_interval: 15

# Allows to monitor the proximity of devices to a particular zone and the direction of travel
proximity:
  home:
    ignored_zones:
      - Home
    devices:
      - device_tracker.iphone_11_plus
    tolerance: 50
    unit_of_measurement: km

# Transmission is now on Integrations
#transmission:
#  host: !secret transmission_ip
#  port: 9091
#  username: !secret transmission_user
#  password: !secret transmission_password

# AirVisual is now on Integrations
#airvisual:
#  api_key: !secret key_airvisual
#  geographies:
#    latitude: !secret geo_lattitude_home
#    longitude: !secret geo_longitude_home

roomba:
  host: !secret roomba_ip
  blid: !secret roomba_blid
  password: !secret roomba_password
  continuous: false

#spotify: - moved to Packages
#  client_id: !secret spotify_id
#  client_secret: !secret spotify_secret
