homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret geo_lattitude_home
  longitude: !secret geo_longitude_home
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 123
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Moscow
  customize: !include customize.yaml
  packages: !include_dir_named packages/
  auth_providers:
    - type: homeassistant
#    - type: legacy_api_password
#      api_password: !secret http_password

# System Health was introduced in 0.87
system_health:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  base_url: !secret http_baseurl
  ip_ban_enabled: true
  login_attempts_threshold: 5

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes/
  javascript_version: latest

# Enables companion component for the Home Assistant iOS app
ios:

# Enables HomeKit
homekit:
  filter:
    include_domains:
      - media_player
      - light
      - switch
  entity_config:
    media_player.onkyo_receiver:
      feature_list:
        - feature: on_off
    media_player.itunes:
      feature_list:
        - feature: on_off
        - feature: play_pause
        - feature: play_stop
        - feature: toggle_mute

# Enables configuration UI
config:

# Embed Hass.IO add-on
panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: http://hassio.local:8080
  logviewer:
    title: Log Viewer
    icon: mdi:script
    url: http://hassio.local:4277
#  grafana:
#    title: Grafana
#    icon: mdi:chart-timeline
#    url: http://hassio.local:3000
#  influxdb:
#    title: InfluxDB
#    url: http://hassio.local:8888

# Adding InfluxDB add-on
#influxdb:
#  host: a0d7b954-influxdb
#  port: 8086
#  database: homeassistant
#  username: !secret influxdb_user
#  password: !secret influxdb_password
#  max_retries: 3
#  default_measurement: state
#  include:
#    entities:
#       - sensor.airport_express_wan_inbound
#       - sensor.airport_express_wan_outbound

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:
  enable:
    - homekit
  ignore:
    - yeelight

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:
recorder:
  purge_keep_days: 31

# Filter events in a logbook
logbook:
  exclude:
    domains:
      - sensor

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Log setup
# Log Severities: notset, debug, info, warn, warning, error, fatal, critical
logger:
  default: info
  logs:
    homeassistant.components.light.yeelight: warning
    homeassistant.components.media_player.itunes: warning
    homeassistant.components.media_player.onkyo_receiver: debug

# Cloud
cloud:

# Enables WOL service
wake_on_lan:

# Macros of Shell commands
shell_command: !include shell.yaml
script: !include scripts.yaml
media_player: !include_dir_merge_list mediaplayers/
sensor: !include_dir_merge_list sensors/
camera: !include_dir_merge_list cameras/
#group: !include groups.yaml

automation: !include automations.yaml
scene: !include scenes.yaml
switch: !include_dir_merge_list switches/
#light: !include lights.yaml

vacuum:
  - platform: roomba
    name: Roomba
    host: !secret ip_roomba
    username: !secret roomba_blid
    password: !secret roomba_password
    continuous: false

weather:
  - platform: yweather
  - platform: openweathermap
    api_key: !secret key_openweathermap

# Text to speech
tts:
  - platform: google
  - platform: yandextts
    api_key: key_yandextts
    language: 'ru-RU'
    codec: mp3
    voice: oksana
    emotion: good
    speed: 2

# Theme selector
input_select: !include input_select.yaml

# Setting zones
zone:
  name: Home
  latitude: !secret geo_lattitude_home
  longitude: !secret geo_longitude_home
  radius: 100
  icon: mdi:home
zone 2:
  name: Office
  latitude: !secret geo_lattitude_office
  longitude: !secret geo_longitude_office
  radius: 200
  icon: mdi:worker

# Yeelight
yeelight:
  devices:
    192.168.1.130:
      name: Living Room
      transition: 800
      use_music_mode: True
    192.168.1.128:
      name: Table Light
      transition: 600
      use_music_mode: True

# Speedtest.com
speedtestdotnet:
  scan_interval:
    minutes: 30
  monitored_conditions:
    - ping
    - download
    - upload
