homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 55.7350667
  longitude: 37.6804702
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 123
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Moscow

  customize:
    switch.mac_mini:
      icon: mdi:monitor
    sensor.moscow:
      icon: mdi:city

# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

logger:
  default: critical
  logs:
    homeassistant.components.light.yeelight: debug
    homeassistant.components.input_select.pcoptions: debug

# Track the sun
sun:

media_player:
  - platform: onkyo
    host: 192.168.1.112
    name: Onkyo Receiver
    sources:
      pc: 'Mac Mini'
      fm: 'FM Tuner'
  - platform: itunes
    host: 192.168.1.103

vacuum:
  - platform: roomba
    name: Roomba
    host: 192.168.1.13
    username: 6977831C70126550
    password: LVvUktdGKTscMRrv

# Weather prediction
sensor:
  - platform: moon
  - platform: worldclock
    time_zone: Etc/UTC
    name: 'UTC'
  - platform: worldclock
    time_zone: America/New_York
    name: 'New York'
  - platform: worldclock
    time_zone: Europe/Moscow
    name: 'Moscow'
  - platform: worldclock
    time_zone: Europe/Paris
    name: 'Paris'
  - platform: worldclock
    time_zone: Asia/Novosibirsk
    name: 'Novosibirsk'
  - platform: yweather
    woeid: 2122265
    name: Weather Moscow
    monitored_conditions:
      - weather
      - weather_current
      - temp_min
      - temp_max
      - wind_speed
      - pressure
      - visibility
      - humidity
      - temperature

# Text to speech
tts:
  - platform: yandextts
    api_key: '1d8ee45e-72ae-4634-8e3c-ef44a2f34b20'
    language: 'ru-RU'
    codec: mp3
    voice: oksana
    emotion: good
    speed: 2

shell_command: !include shell.yaml

group: !include groups.yaml

automation: !include automations.yaml

switch:
  platform: command_line
  switches:
    mac_mini:
      friendly_name: "Mac Mini"
      command_on: "wakeonlan a8:20:66:11:74:81"
      command_off: "ssh twelve@192.168.1.103 pmset sleepnow"
      command_state: "ping -c 1 192.168.1.103"

light:
  - platform: yeelight
    devices:
      192.168.1.101:
        name: Living Room
        transition: 800
      192.168.1.110:
        name: Table Light
        transition: 600
