title: Home
views:
  - id: 0
    title: default_view
    icon: 'mdi:home'
    cards:
      - id: 6f217a92185d41b19ac2013cd67b8ac5
        type: map
        aspect_ratio: 100%
        entities:
          - device_tracker.twelves_iphone8
          - zone.home
          - zone.office
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            title: Light
            show_header_toggle: false
            cards:
              - type: light
                entity: light.table_light
              - type: light
                entity: light.living_room
          - type: entities
            title: Living Room
            show_header_toggle: false
            entities:
              - switch.macmini_wakeonlan
              - vacuum.roomba
      - id: f08dab8a626f42e6b643666bec92637a
        type: media-control
        entity: media_player.itunes
      - id: 487c7b548bb24440ac2a5816e76d2ab2
        type: media-control
        entity: media_player.onkyo_receiver
      - id: 70ccf24a2e70413aabfc40b29ca56d82
        type: entities
        title: Theme Select
        show_header_toggle: false
        entities:
          - input_select.current_theme
      - type: vertical-stack
        cards:
          - type: entities
            title: System Status
            show_header_toggle: false
            entities:
              - entity: sensor.fastcom_download
              - entity: sensor.ipv4_address_eth0
              - entity: sensor.twelves_ipad_rd_battery_level
              - entity: sensor.twelves_iphone_8_battery_level
          - type: entities
            title: Internet
            show_header_toggle: false
            entities:
              - entity: sensor.airport_express_uptime
              - sensor.ssl_europaplusru
              - sensor.ssl_livceycomru
              - sensor.ssl_ykmnsynologyme
              - entity: sensor.europaplusru_domain_name_expiry
          - type: history-graph
            entities:
              - sensor.fastcom_download
              - sensor.processor_use
      - type: vertical-stack
        cards:
          - type: entities
            title: Weather
            show_header_toggle: false
            entities:
              - sun.sun
              - sensor.moon
          - type: weather-forecast
            id: 4221d75de6e44a0588454b84269bf115
            entity: weather.openweathermap
          - type: entities
            title: Clock
            show_header_toggle: false
            entities:
              - sensor.paris
              - sensor.new_york
              - sensor.utc
              - sensor.moscow
              - sensor.novosibirsk
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: entities
                title: Scenes
                show_header_toggle: false
                entities:
                  - scene.im_home
                  - scene.good_night
              - type: entities
                title: Lights Scripts
                show_header_toggle: false
                entities:
                  - entity: script.lights_wakeup
                  - entity: script.lights_sleep
          - type: entities
            title: Automations
            show_header_toggle: false
            entities:
              - automation.allow_change_current_theme
              - automation.auto_set_dark_theme_for_the_night
              - automation.auto_set_bright_theme_for_the_day
              - automation.turn_on_light_at_810
              - automation.turn_off_light_at_915
              - >-
                automation.send_notifications_when_home_assistant_update_available
  - id: 1
    title: Automation
    icon: 'mdi:auto-fix'
    cards:
      - type: entities
        title: Theme Select
        show_header_toggle: false
        entities:
          - input_select.current_theme
      - type: entities
        title: Scenes
        show_header_toggle: false
        entities:
          - scene.im_home
          - scene.good_night
      - type: entities
        title: all automations
        show_header_toggle: false
        entities:
          - entity: automation.allow_change_current_theme
          - entity: automation.auto_set_dark_theme_for_the_night
          - entity: automation.auto_set_bright_theme_for_the_day
          - entity: automation.turn_on_light_at_810
          - entity: automation.turn_off_light_at_915
          - entity: automation.send_notifications_when_home_assistant_update_available
  - id: 2
    title: Weather/Clock
    icon: 'mdi:weather-snowy'
    cards:
      - id: 90784ee2ddc44ca588eba84adcb4277c
        type: weather-forecast
        entity: weather.openweathermap
      - type: entities
        title: Weather
        show_header_toggle: false
        entities:
          - sun.sun
          - sensor.moon
      - type: entities
        title: Clock
        show_header_toggle: false
        entities:
          - sensor.paris
          - sensor.new_york
          - sensor.utc
          - sensor.moscow
          - sensor.novosibirsk
  - id: 3
    title: System Status
    icon: 'mdi:raspberrypi'
    cards:
      - type: entities
        title: System Status
        show_header_toggle: false
        entities:
          - sensor.fastcom_download
          - sensor.ipv4_address_eth0
          - sensor.network_in_eth0
          - sensor.network_out_eth0
          - sensor.processor_use
          - sensor.load_5m
          - sensor.disk_use_percent_
          - sensor.memory_use_percent
      - type: entities
        title: Internet
        show_header_toggle: false
        entities:
          - entity: sensor.airport_express_uptime
      - type: entities
        title: SSL expiry
        show_header_toggle: false
        entities:
          - sensor.ssl_europaplusru
          - sensor.ssl_livceycomru
          - sensor.ssl_ykmnsynologyme
      - type: entities
        title: Domain Names expiry
        show_header_toggle: false
        entities:
          - entity: sensor.europaplusru_domain_name_expiry
