##########################################################################################
# Package Themes /config/packages/package_theme.yaml
##########################################################################################

homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'theme'


##########################################################################################
# Groups
##########################################################################################

group:
  theme_selector:
    name: Theme selector
    icon: mdi:palette
    entities:
      - input_select.set_sunrise_theme
      - input_select.set_sunset_theme
      - sensor.sun_based_theme
      - automation.sun_based_theme_change
      - input_select.theme
##########################################################################################
# Sensors
##########################################################################################

sensor:
  - platform: template
    sensors:
      sun_based_theme:
        friendly_name: Sun based theme
        value_template: >
          {% if is_state('sun.sun','above_horizon') %}
           {{states('input_select.set_sunrise_theme')}}
          {% else %}
            {{states('input_select.set_sunset_theme')}}
          {% endif %}
        icon_template: >
          {% if is_state('sun.sun', 'above_horizon') %}
            mdi:weather-sunny
          {% else %}
            mdi:weather-night
          {% endif %}

##########################################################################################
# Inputs
##########################################################################################

input_select:
  theme:
    name: 'Select Theme'
    icon: mdi:palette
    options:
      - 'default'
      - 'aqua-fiesta'
      - 'amber'
      - 'blue-grey'
      - 'carbon-green'
      - 'Colourful'
      - 'dark'
      - 'dark_teal'
      - 'deep-purple'
      - 'grey'
      - 'hopscotch-dark'
      - 'indigo'
      - 'light-blue'
      - 'midnight'
      - 'noctis'
      - 'nord'
      - 'Orange Light'
      - 'PmxMonolight'
      - 'simple'
      - 'slate'
      - 'solarized'
      - 'solarized-light'
      - 'sublimination'
      - 'synthwave'
      - 'teal'
      - 'vintage'
      - 'wood'
    initial: 'teal'

  set_sunset_theme:
    name: 'Select Sunset theme'
    icon: mdi:weather-night
    options:
      - 'default'
      - 'aqua-fiesta'
      - 'dark'
      - 'dark_teal'
      - 'hopscotch-dark'
      - 'midnight'
      - 'noctis'
      - 'nord'
      - 'slate'
      - 'solarized'
      - 'sublimination'
      - 'synthwave'
      - 'teal'
      - 'vintage'
      - 'wood'
    initial: 'hopscotch-dark'

  set_sunrise_theme:
    name: 'Select Sunrise theme'
    icon: mdi:weather-sunny
    options:
      - 'default'
      - 'amber'
      - 'blue-grey'
      - 'carbon-green'
      - 'Colourful'
      - 'deep-purple'
      - 'grey'
      - 'indigo'
      - 'light-blue'
      - 'Orange Light'
      - 'PmxMonolight'
      - 'solarized-light'
      - 'teal'
      - 'vintage'
      - 'wood'
    initial: 'Colourful'

##########################################################################################
# Automations
##########################################################################################

automation:
  - alias: 'Change Current Theme'
    id: 'Change Current Theme'
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: input_select.theme
    action:
      service: frontend.set_theme
      data_template:
        name: >
          {{states('input_select.theme')}}

  - alias: Sun based theme change
    id: 'Sun based theme change'
#    initial_state: 'on'
    trigger:
      - platform: homeassistant
        event: start
#      - platform: state
#        entity_id: input_select.set_sunset_theme
#      - platform: state
#        entity_id: input_select.set_sunrise_theme
      - platform: state
        entity_id: sensor.sun_based_theme
#      - platform: sun
#        event: sunrise
#      - platform: sun
#        event: sunset
#      - platform: state
#        entity_id: sun.sun
#        to: above_horizon
#      - platform: state
#        entity_id: sun.sun
#        to: below_horizon
    condition: []
    action:
#      - delay:
#          seconds: 3
      - service_template: frontend.set_theme
        data_template:
          name: >
            {{ states('sensor.sun_based_theme') }}
#            {% if trigger.platform == 'sun' %}
#              {{states('input_select.set_sunset_theme') if trigger.event == 'sunset' else
#                states('input_select.set_sunrise_theme') }}
#            {% else %}
#              {{ states('sensor.sun_based_theme') }}
#            {% endif %}
      - condition: template
        value_template: >
          {{ is_state('input_boolean.notify_system', 'on')}}
      - service: notify.notify
        data_template:
          message: >
            {{ as_timestamp(now()) | timestamp_custom("%X") }}:
            Sun is {{states('sun.sun')}} and Frontend is set to '{{ states('sensor.sun_based_theme') }}'
