plant:
  saintpaulia:
    min_moisture: 15
    max_moisture: 60
    min_conductivity: 500
    min_temperature: 18
    min_battery: 10
    sensors:
      moisture: sensor.mi_flora_moisture
      battery: sensor.mi_flora_battery
      temperature: sensor.mi_flora_temperature
      conductivity: sensor.mi_flora_conductivity
      brightness: sensor.mi_flora_brightness

sensor:
  - platform: miflora
    mac: 'C4:7C:8D:6B:84:60'
    name: Mi Flora
    go_unavailable_timeout: 43200
    monitored_conditions:
      - moisture
      - light
      - temperature
      - conductivity
      - battery

homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'flora'
    plant.saintpaulia:
      friendly_name: Saintpaulia
