homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'MediaPlayers'

notify:
  - platform: file
    name: entity_log
    filename: /config/www/entity_log.txt
    timestamp: false

script:
  print_entities_to_file:
    alias: 'Print All Entities To File'
    sequence:
    - service: notify.entity_log
      data_template:
        message: >
          {% for state in states %}
            {{-'- ' + state.entity_id }}
          {% endfor %}
